[project]
name = "dodo"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "fastapi[standard]>=0.128.6",
  "psycopg>=3.3.2",
  "psycopg2>=2.9.11",
  "pydantic>=2.12.5",
  "pyjwt>=2.11.0",
  "requests>=2.32.5",
  "shared",
  "sqlmodel>=0.0.32",
]
[tool.basedpyright]
include = ["packages", "services"]
extraPaths = ["packages/shared"]
exclude = ["**/__pycache__", "src/experimental", "src/typestubs"]
ignore = ["docs"]
defineConstant = { DEBUG = true }

typeCheckingMode = "basic"
diagnosticMode = "openFilesOnly"
useLibraryCodeForTypes = false

reportMissingImports = "error"
reportMissingTypeStubs = false

pythonVersion = "3.11"
pythonPlatform = "Linux"

executionEnvironments = [
  { root = "packages/shared", extraPaths = ["packages/shared"] },
  { root = "packages", extraPaths = ["packages/shared"] },
  { root = "services", extraPaths = ["packages/shared"] },
  { root = "tests", extraPaths = ["packages/shared"] },
]

[tool.uv.workspace]
members = ["tests", "packages/shared"]

[tool.uv.sources]
shared = { workspace = true }
