[project]
name = "dodo-activity-api"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "fastapi[standard]>=0.128.6",
  "sqlmodel>=0.0.22",
  "psycopg2-binary>=2.9.0",
  "uvicorn[standard]>=0.24.0",
  "shared",
]

[tool.uv.sources]
shared = { path = "/workspace/packages/shared", editable = true }
